// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWPPFqy50MhQFDHz3mjFZdJHJp8MrdAvs',
    appId: '1:116429891373:web:5054170d0e7e3d8d72d5a4',
    messagingSenderId: '116429891373',
    projectId: 'universityproject-c2787',
    authDomain: 'universityproject-c2787.firebaseapp.com',
    storageBucket: 'universityproject-c2787.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRdbE5vCg8mw-lxQLbTQYB1pT1wBoh5Ps',
    appId: '1:116429891373:android:97290fd3c9e7c13c72d5a4',
    messagingSenderId: '116429891373',
    projectId: 'universityproject-c2787',
    storageBucket: 'universityproject-c2787.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKDEfJyB5PwEO1G_6RXr0MTK0UbpJApj8',
    appId: '1:116429891373:ios:8fe5727dde5cd54672d5a4',
    messagingSenderId: '116429891373',
    projectId: 'universityproject-c2787',
    storageBucket: 'universityproject-c2787.firebasestorage.app',
    iosBundleId: 'com.example.mediGr2Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKDEfJyB5PwEO1G_6RXr0MTK0UbpJApj8',
    appId: '1:116429891373:ios:8fe5727dde5cd54672d5a4',
    messagingSenderId: '116429891373',
    projectId: 'universityproject-c2787',
    storageBucket: 'universityproject-c2787.firebasestorage.app',
    iosBundleId: 'com.example.mediGr2Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWPPFqy50MhQFDHz3mjFZdJHJp8MrdAvs',
    appId: '1:116429891373:web:0d8666c94dd4433572d5a4',
    messagingSenderId: '116429891373',
    projectId: 'universityproject-c2787',
    authDomain: 'universityproject-c2787.firebaseapp.com',
    storageBucket: 'universityproject-c2787.firebasestorage.app',
  );
}
